target-version = "py311"

# Same as Black.
line-length = 88
indent-width = 4

[lint]
extend-select = [
    "UP",
    "TRY",
    "I",
    "SIM",
    "C90",
    "D201",
    "D202",
    "PLR",
    "D100",
    "D102",
    "D103",
    "D104",
    "D300",
    "D419",
    "E501",

]

ignore = ["PLR0402","PLR0911"]

[lint.per-file-ignores]
"tests/**/*.py" = [
    "D100", # Ignore missing docstrings for public modules
    "D103", # Ignore missing docstrings for public functions
]

[lint.pydocstyle]
# Use Google-style docstrings
convention = "google"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
