name: Backend Tests - Database Blob

on:
  pull_request:
    branches:
      - 'master'
      - 'master-*'

jobs:
  run_tests_blob_architecture:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Install dependencies
        working-directory: Backend
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Run tests Database Blob Architecture
        working-directory: Backend/
        run: |
          python -m pytest .
        env:
          MONGO_URI: mongodb://root:root@localhost:27017/
          SECRET_KEY_SIGN: ${{ secrets.SECRET_KEY_SIGN }}
          SERVERLESS_FUNCTION_URL: ${{ secrets.SERVERLESS_FUNCTION_URL }}
          ARCH: "BLOB"
          ENV_VALUE: "PROD"

      - name: Fail workflow on test failure
        if: ${{ failure() }}
        run: exit 1
